### ISSUE TITLE
Project languages should be recognised.

### ISSUE THREAD

**Issue by phish108** [sustainability-zhaw/extraction-projects#5]
the project DB appears to have two primary languages: German and English

Currently, all projects are recognised as German, despite several of them contain only English information. 

The english language should be properly recognised. 

May this could/Should be done in a special resolver?

@stlozhaw what do you think?

**Comment by stlozhaw** [comment]
@phish108 Should we try to detect the language with nlp?

**Comment by phish108** [comment]
I would do the naive approach and check whether german and English are the same, in which case its English, i guess.

**Comment by stlozhaw** [comment]
Yes, let's do that.
